In [1]:
import pandas as pd
from sklearn.naive_bayes import GaussianNB
import numpy as np
from sklearn.utils.validation import column_or_1d
import pickle
from sklearn.preprocessing import LabelEncoder

In [2]:
data = pd.read_excel('playgolf_data.xlsx', index_col = 0)
data.head()

Outlook Temperature Humidity    Wind Play Golf
Day                                                 
1       Sunny         Hot     High    Weak        No
2       Sunny         Hot     High  Strong        No
3    Overcast         Hot     High    Weak       Yes
4        Rain        Mild     High    Weak       Yes
5        Rain        Cool   Normal    Weak       Yes

In [4]:
features=data.drop('Play Golf', axis=1)
target=data[['Play Golf']]

In [5]:
features =pd.get_dummies(features)
features

Outlook_Overcast  Outlook_Rain  Outlook_Sunny  Temperature_Cool  \
Day                                                                    
1                   0             0              1                 0   
2                   0             0              1                 0   
3                   1             0              0                 0   
4                   0             1              0                 0   
5                   0             1              0                 1   
6                   0             1              0                 1   
7                   1             0              0                 1   
8                   0             0              1                 0   
9                   0             0              1                 1   
10                  0             1              0                 0   
11                  0             0              1                 0   
12                  1             0              0                 0   
13                  1             0              0                 0   
14                  0             1              0                 0   

     Temperature_Hot  Temperature_Mild  Humidity_High  Humidity_Normal  \
Day                                                                      
1                  1                 0              1                0   
2                  1                 0              1                0   
3                  1                 0              1                0   
4                  0                 1              1                0   
5                  0                 0              0                1   
6                  0                 0              0                1   
7                  0                 0              0                1   
8                  0                 1              1                0   
9                  0                 0              0                1   
10                 0                 1              0                1   
11                 0                 1              0                1   
12                 0                 1              1                0   
13                 1                 0              0                1   
14                 0                 1              1                0   

     Wind_Strong  Wind_Weak  
Day                          
1              0          1  
2              1          0  
3              0          1  
4              0          1  
5              0          1  
6              1          0  
7              1          0  
8              0          1  
9              0          1  
10             0          1  
11             1          0  
12             1          0  
13             0          1  
14             1          0

In [8]:
le = LabelEncoder()
target=le.fit_transform(column_or_1d(target))
target

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0], dtype=int64)

In [9]:
model=GaussianNB()
model.fit(features, column_or_1d(target))

GaussianNB(priors=None, var_smoothing=1e-09)

In [10]:
print('Prediction accuracy: ', model.score(features, np.array(target))*100,'%')

Prediction accuracy:  64.28571428571429 %


In [11]:
from sklearn.naive_bayes import BernoulliNB

In [12]:
model1=BernoulliNB()
model1=model1.fit(features, target)

In [14]:
print('Prediction accuracy: ', model1.score(features, (target))*100,'%')

Prediction accuracy:  92.85714285714286 %


In [15]:
class_names = model1.classes_
class_names

array([0, 1], dtype=int64)

In [17]:
# Save to file in the current working directory
pkl_filename = 'playgoft_model.pkl'
with open(pkl_filename, 'wb') as file:
    pickle.dump(model1,file)

In [20]:
with open(pkl_filename, 'rb') as file:
    playgoft_model = pickle.load(file)

In [21]:
# X_test = [['Overcast','Cool','High','Strong'],['Sunny','Cool','High','Weak']]
X_test=[[1,0,0,1,0,0,1,0,1,0],[0,0,1,1,0,0,1,0,0,1]]
y_pred=playgoft_model.predict(X_test)
y_pred

array([1, 0], dtype=int64)